MODEL:
  META_ARCHITECTURE: "PixelCLIP"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "PixelCLIPHead"
    IN_FEATURES: ["res2", "res3", "res4"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 64
    TRAIN_CLASS_JSON: "datasets/coco.json"
    TEST_CLASS_JSON: "datasets/ade150.json"
    PROMPT_LENGTH: 4
    CLIP_PRETRAINED: "ViT-B/16"
    CLIP_FINETUNE: "attention"
  PROMPT_ENSEMBLE_TYPE: "single"
DATASETS:
  TRAIN: ("sam_resized",)
  TEST: ("ade20k_150_test_sem_seg",)
SOLVER:
  IMS_PER_BATCH: 48
  BASE_LR: 0.0002
  BASE_LR_END: 0.0001
  MAX_ITER: 10000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  PROMPT_MULTIPLIER: 10.0
  CLIP_MULTIPLIER: 0.01
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  STRONG_AUG: True
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  MIN_SIZE_TRAIN: (1024, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 2560
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 640
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: SamBaselineDatasetMapperJSON
TEST:
  EVAL_PERIOD: 1000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2
CUDNN_BENCHMARK: True